import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "@/contexts/userContext";
import Styles from "../styles/home-page.module.scss";
import AuthGate from "@/contexts/AuthGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Teke a Seat",
  description: "Generated by Luca Gattamelata",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserContextProvider>
          <AuthGate>
            <div className={Styles.container}>{children}</div>
          </AuthGate>
        </UserContextProvider>
      </body>
    </html>
  );
}
