/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/complete-profile`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/just-book-me-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(access)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(access)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(access)'}/update-password` | `/update-password`; params?: Router.UnknownInputParams; } | { pathname: `/restaurant/[id]/dishes`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/restaurant/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/restaurant/[id]/reviews`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/restaurant/[id]/tables`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/restaurant/[id]/components/FavouriteStarButton`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/restaurant/[id]/components/LayoutContent`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/restaurant/[id]/components/RestaurantNavbar`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/complete-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/just-book-me-in`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(access)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(access)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(access)'}/update-password` | `/update-password`; params?: Router.UnknownOutputParams; } | { pathname: `/restaurant/[id]/dishes`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/restaurant/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/restaurant/[id]/reviews`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/restaurant/[id]/tables`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/restaurant/[id]/components/FavouriteStarButton`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/restaurant/[id]/components/LayoutContent`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/restaurant/[id]/components/RestaurantNavbar`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/complete-profile${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/just-book-me-in${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(access)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(access)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(access)'}/update-password${`?${string}` | `#${string}` | ''}` | `/update-password${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/complete-profile`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/just-book-me-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(access)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(access)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(access)'}/update-password` | `/update-password`; params?: Router.UnknownInputParams; } | `/restaurant/${Router.SingleRoutePart<T>}/dishes` | `/restaurant/${Router.SingleRoutePart<T>}` | `/restaurant/${Router.SingleRoutePart<T>}/reviews` | `/restaurant/${Router.SingleRoutePart<T>}/tables` | `/restaurant/${Router.SingleRoutePart<T>}/components/FavouriteStarButton` | `/restaurant/${Router.SingleRoutePart<T>}/components/LayoutContent` | `/restaurant/${Router.SingleRoutePart<T>}/components/RestaurantNavbar` | { pathname: `/restaurant/[id]/dishes`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/restaurant/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/restaurant/[id]/reviews`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/restaurant/[id]/tables`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/restaurant/[id]/components/FavouriteStarButton`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/restaurant/[id]/components/LayoutContent`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/restaurant/[id]/components/RestaurantNavbar`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
